/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/LUuAF65qJTG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select } from "@/components/ui/select"

export default function trialHomeComponent() {
  return (
    <>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-900">
        <div className="container px-4 md:px-6">
          <div className="grid items-center gap-6 lg:grid-cols-2 lg:gap-12">
            <div className="space-y-4">
              <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-[4.5rem]">
                Unlock Your Fitness Potential
              </h1>
              <p className="max-w-[600px] text-gray-600 dark:text-gray-400 md:text-xl/relaxed">
                Experience the best gym in town with state-of-the-art equipment, expert trainers, and a vibrant
                community.
              </p>
              <div className="flex flex-col sm:flex-row items-start gap-4">
                <Button variant="primary">Join Now</Button>
                <Link
                  className="inline-flex items-center gap-2 text-gray-900 dark:text-gray-50 hover:underline underline-offset-4"
                  href="#"
                >
                  Learn More
                  <ArrowRightIcon className="h-5 w-5" />
                </Link>
              </div>
            </div>
            <img
              alt="Hero"
              className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              height="550"
              src="/placeholder.svg"
              width="550"
            />
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="grid gap-12 lg:grid-cols-3">
            <div className="space-y-4 text-center">
              <DumbbellIcon className="mx-auto h-12 w-12 text-gray-900 dark:text-gray-50" />
              <h3 className="text-2xl font-bold">State-of-the-Art Gym</h3>
              <p className="text-gray-600 dark:text-gray-400">
                Our gym is equipped with the latest fitness technology and machines to help you reach your goals.
              </p>
            </div>
            <div className="space-y-4 text-center">
              <ActivityIcon className="mx-auto h-12 w-12 text-gray-900 dark:text-gray-50" />
              <h3 className="text-2xl font-bold">Diverse Class Offerings</h3>
              <p className="text-gray-600 dark:text-gray-400">
                From yoga and Pilates to HIIT and spin, we have a wide range of classes to suit every fitness level.
              </p>
            </div>
            <div className="space-y-4 text-center">
              <PersonStandingIcon className="mx-auto h-12 w-12 text-gray-900 dark:text-gray-50" />
              <h3 className="text-2xl font-bold">Personalized Training</h3>
              <p className="text-gray-600 dark:text-gray-400">
                Our experienced trainers will work with you one-on-one to create a customized workout plan.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-900">
        <div className="container px-4 md:px-6">
          <div className="grid items-center gap-6 lg:grid-cols-2 lg:gap-12">
            <div className="space-y-4">
              <h2 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Membership Plans</h2>
              <p className="max-w-[600px] text-gray-600 dark:text-gray-400 md:text-xl/relaxed">
                Choose the plan that fits your fitness goals and budget.
              </p>
              <div className="grid gap-4">
                <Card>
                  <CardHeader>
                    <CardTitle>Monthly Membership</CardTitle>
                    <CardDescription>Flexible plan with no long-term commitment.</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="flex items-end gap-2">
                      <span className="text-4xl font-bold">$49</span>
                      <span className="text-gray-600 dark:text-gray-400">/month</span>
                    </div>
                    <ul className="space-y-2 text-gray-600 dark:text-gray-400">
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-gray-900 dark:text-gray-50" />
                        Access to all gym facilities
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-gray-900 dark:text-gray-50" />
                        Unlimited group classes
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-gray-900 dark:text-gray-50" />
                        Personal training sessions
                      </li>
                    </ul>
                  </CardContent>
                  <CardFooter>
                    <Button variant="primary">Join Now</Button>
                  </CardFooter>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Annual Membership</CardTitle>
                    <CardDescription>Save 20% with an annual commitment.</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="flex items-end gap-2">
                      <span className="text-4xl font-bold">$499</span>
                      <span className="text-gray-600 dark:text-gray-400">/year</span>
                    </div>
                    <ul className="space-y-2 text-gray-600 dark:text-gray-400">
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-gray-900 dark:text-gray-50" />
                        Access to all gym facilities
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-gray-900 dark:text-gray-50" />
                        Unlimited group classes
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-gray-900 dark:text-gray-50" />
                        Personal training sessions
                      </li>
                    </ul>
                  </CardContent>
                  <CardFooter>
                    <Button variant="primary">Join Now</Button>
                  </CardFooter>
                </Card>
              </div>
            </div>
            <div className="space-y-4">
              <h2 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Sign Up Today</h2>
              <p className="max-w-[600px] text-gray-600 dark:text-gray-400 md:text-xl/relaxed">
                Fill out the form below to get started with your membership.
              </p>
              <form className="space-y-4">
                <div className="grid gap-4 sm:grid-cols-2">
                  <div className="space-y-1">
                    <Label htmlFor="name">Name</Label>
                    <Input id="name" placeholder="Enter your name" type="text" />
                  </div>
                  <div className="space-y-1">
                    <Label htmlFor="email">Email</Label>
                    <Input id="email" placeholder="Enter your email" type="email" />
                  </div>
                </div>
                <div className="space-y-1">
                  <Label htmlFor="password">Password</Label>
                  <Input id="password" placeholder="Enter a password" type="password" />
                </div>
                <div className="space-y-1">
                  <Label htmlFor="plan">Membership Plan</Label>
                  <Select id="plan">
                    <option value="monthly">Monthly Membership</option>
                    <option value="annual">Annual Membership</option>
                  </Select>
                </div>
                <div className="space-y-1">
                  <Label htmlFor="payment">Payment Method</Label>
                  <Input id="payment" placeholder="Enter your payment details" type="text" />
                </div>
                <Button type="submit" variant="primary">
                  Sign Up
                </Button>
              </form>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

function ActivityIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2" />
    </svg>
  )
}


function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function DumbbellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.4 14.4 9.6 9.6" />
      <path d="M18.657 21.485a2 2 0 1 1-2.829-2.828l-1.767 1.768a2 2 0 1 1-2.829-2.829l6.364-6.364a2 2 0 1 1 2.829 2.829l-1.768 1.767a2 2 0 1 1 2.828 2.829z" />
      <path d="m21.5 21.5-1.4-1.4" />
      <path d="M3.9 3.9 2.5 2.5" />
      <path d="M6.404 12.768a2 2 0 1 1-2.829-2.829l1.768-1.767a2 2 0 1 1-2.828-2.829l2.828-2.828a2 2 0 1 1 2.829 2.828l1.767-1.768a2 2 0 1 1 2.829 2.829z" />
    </svg>
  )
}


function PersonStandingIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="5" r="1" />
      <path d="m9 20 3-6 3 6" />
      <path d="m6 8 6 2 6-2" />
      <path d="M12 10v4" />
    </svg>
  )
}
